package me.pljr.pljrapi.enums;

public enum Lang {
    NO_PERM,
    NO_NUMBER,
    NO_MATERIAL,
    OFFLINE,
    TIME_FORMAT_DAYS,
    TIME_FORMAT_HOURS,
    TIME_FORMAT_MINUTES,
    COMMAND_RESPONSE_PLAYER,
    COMMAND_RESPONSE_CONSOLE
}
