name: PLJRApi-Spigot
version: ${project.version}
main: me.pljr.pljrapispigot.PLJRApiSpigot
api-version: 1.13
authors: [9hx]
softdepend: [Vault, PlaceholderAPI, HolographicDisplays]
description: API for all of my plugins.
